INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:01:43] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:01:43] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:01:43] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:01:43] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:02:15] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:02:15] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:08:23] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:08:23] "GET /api/v1/mentor/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:08:28] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:08:28] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:08:33] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:08:33] "GET /api/v1/mentor/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:09:13] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:09:13] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:09:13] "OPTIONS /api/v1/mentor/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:09:13] "[31m[1mGET /api/v1/mentor/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:09:21] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:09:21] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:09:21] "[31m[1mGET /api/v1/mentor/home HTTP/1.1[0m" 401 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/backend/run.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:10:15] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/backend/run.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/backend/run.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:15:08] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:15:08] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:15:08] "[31m[1mGET /api/v1/mentor/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:15:32] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:15:32] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:15:32] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:16:01] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:16:01] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:16:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/backend/run.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/backend/app/controller/login_controller.py", line 10, in login
    return fun_login()
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/backend/app/services/login.py", line 12, in fun_login
    data = request.json
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 561, in json
    return self.get_json()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 607, in get_json
    return self.on_json_loading_failed(None)
  File "/usr/local/lib/python3.8/dist-packages/flask/wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 650, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:23:43] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 415 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:26:50] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:26:50] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:26:50] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:27:21] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:27:21] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:27:21] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:27:59] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:27:59] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:27:59] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:41:31] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py", line 46, in admin_home
    return fun_admin_home()
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py", line 43, in fun_admin_home
    'Username':user[5],
TypeError: 'NoneType' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:41:32] "[35m[1mGET /api/v1/admin/home HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:42:29] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:42:48] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py", line 46, in admin_home
    return fun_admin_home()
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py", line 43, in fun_admin_home
    'Username':user[5],
TypeError: 'NoneType' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:42:48] "[35m[1mGET /api/v1/admin/home HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:45:36] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py", line 46, in admin_home
    return fun_admin_home()
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py", line 43, in fun_admin_home
    'Username':user[5],
TypeError: 'NoneType' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:45:36] "[35m[1mGET /api/v1/admin/home HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:49:20] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 17:49:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:50] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:51] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:55] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:55] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:59] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:59] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:59] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:09:59] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:12:55] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:12:56] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:12:56] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Feb/2024 18:12:56] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:04] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:04] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:14] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:14] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:20] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:20] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:37] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:58] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:31:58] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:32:39] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:32:39] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:39:13] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:39:13] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:39:13] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:39:13] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:41:05] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:41:06] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:41:06] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:41:06] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:42:52] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:42:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:42:57] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:42:57] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:43:35] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:43:36] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:43:36] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 09:43:36] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:04:53] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:04:53] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:04:53] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:04:53] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/login_controller.py", line 10, in login
    return fun_login()
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py", line 12, in fun_login
    data = request.json
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py", line 561, in json
    return self.get_json()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py", line 607, in get_json
    return self.on_json_loading_failed(None)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py", line 650, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:08:47] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 415 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:08:59] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:08:59] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:09:04] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:09:04] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:13:06] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:13:07] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:13:07] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:13:07] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:16:31] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:16:31] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:16:43] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:16:43] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:16:43] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:16:43] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:20:06] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:20:06] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:20:06] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:22:01] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:22:01] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:25:08] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:25:08] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:25:08] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:25:08] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:32:39] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:32:39] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:32:39] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:32:39] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:32:42] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:32:42] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:33:02] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:33:03] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:33:03] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:33:03] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:34:15] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:34:16] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:34:16] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:34:16] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:34:27] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:34:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:37:20] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:37:31] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:37:31] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:37:35] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:37:35] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:41:40] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:41:40] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:41:40] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:41:40] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:45:41] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:45:41] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:45:41] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:45:41] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:49:51] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:49:51] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:52:53] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:52:53] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:52:53] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:52:53] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:58:35] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:58:36] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:58:36] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 10:58:36] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:00:45] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:00:46] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:00:46] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:00:46] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:01:35] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:01:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:01:40] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:01:40] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:06:24] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:06:24] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:06:24] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:06:24] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:14:39] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:14:39] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:14:39] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:14:39] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:15:58] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:15:58] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:15:58] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:15:58] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:16:02] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:16:02] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:03] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:03] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:03] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:03] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:15] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:16] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:16] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:16] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:17] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:17] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:18] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:18] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:20] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:19:20] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:20:20] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:20:20] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:20:20] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:20:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:20:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:20:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:20:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:42] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:42] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:49] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:50] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:50] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:50] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:50] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:50] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:21:50] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:00] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:05] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:10] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:16] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:24] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:24] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:40] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:40] "[32mPOST /api/v1/login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:40] "OPTIONS /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:40] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:41] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:41] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:41] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:46] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:22:58] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 11:59:58] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:02:20] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:02:22] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:02:37] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:02:37] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:02:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:02:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:02:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:04:13] "[31m[1mPOST /api/v1/admin/home HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:20:57] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:20:58] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:04] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:04] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:15] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:16] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:42] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:42] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:42] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:21:42] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/run.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:29:17] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:29:17] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:29:17] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:29:17] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:03] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:04] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:31] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:31] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:31] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:30:31] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:46] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:46] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:46] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:46] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:55] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:55] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:55] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:32:55] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:03] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:04] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:29] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:29] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:34:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:36:44] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:36:45] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:36:55] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:36:56] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:36:56] "[33mGET /api/v1/admin/home HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:36:56] "[33mGET /api/v1/admin/home HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:37:23] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:37:23] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:37:23] "[33mGET /api/v1/admin/home HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:37:23] "[33mGET /api/v1/admin/home HTTP/1.1[0m" 404 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:14] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:15] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:43] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:43] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:43] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:43] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:43] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:43] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:44] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:44] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:44] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:44] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:59] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:41:59] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:00] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:42:01] "[31m[1mGET /api/v1/admin/home HTTP/1.1[0m" 401 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:59:39] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:59:39] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:59:39] "[33mGET /api/v1/admin/id HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 12:59:39] "[33mGET /api/v1/admin/id HTTP/1.1[0m" 404 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:00:53] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:00:53] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:00:53] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:00:53] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:00:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:00:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:04:07] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:04:07] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:04:07] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:04:07] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:04:07] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:04:07] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:27] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:32] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:32] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:46] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:47] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:47] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:47] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:47] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:07:47] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:13] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:14] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:14] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:14] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:14] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:14] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:20] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:20] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:20] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:20] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:08:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:09:37] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:09:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:09:56] "GET /api/v1/admin/id HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 13:09:56] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:12:50] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:12:50] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:12:50] "[33mGET /api/v1/admin/id HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:12:50] "[33mGET /api/v1/admin/id HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:31:15] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:31:15] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:31:15] "[33mGET /api/v1/admin/id HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:31:15] "[33mGET /api/v1/admin/id HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:44:58] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:44:58] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:45:18] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:45:19] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:45:19] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:45:19] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:24] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:30] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:30] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:30] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:30] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:41] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:42] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:42] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:46:42] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:20] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:21] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:21] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:21] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:30] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:31] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:31] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:55:31] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/run.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/run.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:58:51] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:58:52] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:58:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:58:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:59:01] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:59:02] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:59:02] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 15:59:02] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 16:13:53] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 16:13:53] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 16:19:00] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 16:19:01] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 16:19:01] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 16:19:01] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 17:13:50] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 17:13:50] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 17:13:50] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 17:13:50] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:10:19] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:10:21] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:10:27] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:10:49] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:10:49] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:02] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:03] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:11] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:12] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:27] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:28] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:50] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 18:11:51] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:02] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:02] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:02] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:02] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:09] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:09] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:18] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:18] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:18] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:18] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:21] "[32mPOST /api/v1/logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:19:21] "GET /api/v1/temp HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug: * Detected change in '/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:23:43] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:23:44] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:23:54] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:23:55] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:24:19] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:24:19] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:25:24] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:25:25] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:26:10] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:26:11] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:28] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:28] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:28] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:28] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:31] "POST /api/v1/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:44] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:44] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:44] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:28:44] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:29:10] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:29:11] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:29:11] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:29:11] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:29:19] "POST /api/v1/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:32:25] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:32:25] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:32:25] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:32:25] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Feb/2024 19:32:28] "POST /api/v1/logout HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 11:47:45] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 11:48:28] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 11:48:28] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 14:53:48] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 14:53:51] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 14:54:00] "[33mGET /api/admin/home HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 14:54:32] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 15:40:07] "[33mGET /api/admin/home HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [18/Feb/2024 15:40:07] "[33mGET /api/admin/home HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:57:12] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:57:13] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 609-915-266
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:58:10] "POST /api/v1/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:58:22] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:58:22] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:58:31] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:58:31] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 12:58:36] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:00:58] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:00:58] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:03:40] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:04:15] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:04:25] "[31m[1mPOST /api/v1/admin/home HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:04:35] "POST /api/v1/admin/createUser HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:07:08] "POST /api/v1/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:07:15] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:07:16] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:07:36] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:07:37] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:08:02] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:09:48] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:09:48] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:10:02] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:10:02] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:10:03] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:10:37] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:25:41] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:26:05] "[33mGET /api/admin/home HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:26:40] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:26:43] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 13:26:43] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:22:27] "[33mGET /main.2ee2ee3cdc6dd569108c.hot-update.json HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:22:29] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:22:29] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:22:58] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:23:04] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:23:09] "POST /api/v1/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:23:55] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:31:12] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:32:46] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:35:46] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:36:31] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:39:16] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:43:40] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:44:36] "POST /api/v1/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:44:46] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:44:54] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:45:10] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:45:17] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:45:25] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:45:58] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 14:47:32] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:03:03] "[33mGET /main.d08d9f9e62ec80cbbcef.hot-update.json HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:03:03] "[33mGET /main.d08d9f9e62ec80cbbcef.hot-update.json HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:03:05] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:03:10] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:03:11] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:03:30] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:03:32] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:04:43] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:08:48] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:09:57] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:09:57] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:10:14] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:10:14] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:11:01] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:11:09] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:17:05] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:17:15] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:24:03] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:36:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 650, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:37:56] "[31m[1mGET /api/v1/login HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:38:07] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:38:10] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/controller/admin_controller.py", line 34, in admin_remove_user
    return fun_admin_delete_user()
  File "/home/adilmohamedparayil/Desktop/Mini Project/userprofilemanagement-1/app/services/admin.py", line 316, in fun_admin_delete_user
    role_type = cursor.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:39:00] "[35m[1mDELETE /api/v1/admin/removeUser?username=USRX241002 HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:39:31] "DELETE /api/v1/admin/removeUser?username=student1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:40:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:49:26] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:49:27] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:49:51] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:56:21] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:57:26] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 15:57:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 16:11:32] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 16:11:43] "GET /api/v1/student/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 16:15:54] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 16:16:42] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:10:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:10:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:13:51] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:20:48] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:21:47] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:22:34] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:27:43] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:28:03] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:31:59] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:32:39] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:33:02] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:36:27] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:36:33] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:36:54] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:43:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:49:00] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:55:28] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 17:56:23] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:04:18] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:04:32] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:07:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:07:23] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:07:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:08:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:08:36] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:10:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:15:43] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:15:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Feb/2024 18:15:58] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:44:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:44:15] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:45:03] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:45:06] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:45:58] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:48:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:51:48] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:54:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:54:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:54:58] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:03] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:05] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:07] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:09] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:11] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:13] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:18] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:45] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:47] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:50] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:56] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:55:59] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:56:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:56:14] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:58:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:58:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:58:06] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:58:09] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:59:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:59:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:59:41] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:59:43] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 09:59:51] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:01:24] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:01:28] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:04:42] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:05:09] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:06:14] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:06:39] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:06:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:07:17] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:08:17] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:08:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:10:08] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:17:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:18:21] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:20:42] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:20:57] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:23:03] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:23:11] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 10:27:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 11:08:24] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 11:08:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 11:10:31] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 11:13:04] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:12:09] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:13:10] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:17:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:18:33] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:20:24] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:21:25] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:21:49] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:23:55] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:27:27] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:29:09] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:29:22] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:34:17] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:36:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 12:53:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 13:15:05] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 14:58:14] "[33mGET /main.16129b198caab372153d.hot-update.json HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 14:59:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 14:59:36] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 15:02:31] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 15:02:39] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 15:04:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 15:39:38] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 15:39:42] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 15:40:08] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 17:23:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 17:44:46] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 18:12:41] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 18:12:54] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 18:13:07] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Feb/2024 18:13:13] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:17:06] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:28:56] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:33:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:33:58] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:38:20] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:38:48] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:39:26] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:46:13] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:56:10] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 09:56:15] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 10:26:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 11:33:38] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 11:34:12] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:03:35] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:11:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:21:54] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:21:59] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:32] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:38] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:40] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:43] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:45] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:49] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:52] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:22:54] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:01] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:05] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:07] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:10] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:19] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:22] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:26] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:23:34] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:25:39] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:26:03] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:26:46] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:27:13] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:27:53] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:28:10] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:28:43] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:29:07] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:29:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:29:39] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:30:28] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:30:35] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:31:56] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:32:36] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:32:41] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:34:15] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:34:26] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:34:45] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:36:29] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:36:37] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:36:44] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:38:25] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:38:25] "POST /api/v1/login HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:41:16] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:41:26] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:41:27] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:42:22] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:42:23] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:43:24] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:43:25] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:45:00] "GET /api/v1/admin/home HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/adilmohamedparayil/.local/lib/python3.8/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:45:00] "[33mGET /main.42a4b4cfaad9495e358a.hot-update.js HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:46:50] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:46:50] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:46:54] "[31m[1mPOST /api/v1/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:47:01] "OPTIONS /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:47:01] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:48:06] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:48:06] "GET /api/v1/admin/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:49:00] "POST /api/v1/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Feb/2024 12:49:03] "GET /api/v1/admin/home HTTP/1.1" 200 -
